version: '3.4'

services:
  webhooksystem:
    image: ${DOCKER_REGISTRY-}webhooksystem
    build:
      context: .
      dockerfile: WebHookSystem/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=webhookuser
      - POSTGRES_PASSWORD=webhookpassword
      - POSTGRES_DB=webhookdb
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:80"
    networks:
      - webhooknet  

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: webhookuser
      POSTGRES_PASSWORD: webhookpassword
      POSTGRES_DB: webhookdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webhooknet 

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - webhooknet  

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - webhooknet  

volumes:
  postgres_data:  

networks:
  webhooknet:  
    driver: bridge  
